#! /bin/sh
# 
# This script is merely intended for developers to use to run console from
# the development directory, and is not needed or meant for installation.

if [ -f build/src/console/console ]
then
    build/src/console/console "$@"
else
    echo "Run './waf configure build' first."
fi

