#! /usr/bin/env python
# encoding: utf-8
#
# Copyright 2011-2012 Yorba Foundation

theseus_src = [
'theseus.vala'
]

theseus_uselib = 'GEE GTK GLIB'
theseus_packages = [ 'gee-1.0', 'glib-2.0' ]

bld.program(
	target		= 'theseus',
	vapi_dirs	= '../../vapi',
	threading	= True,
	use			='geary-static',
	uselib		= theseus_uselib + ' ' + bld.engine_uselib + ' ' + bld.common_uselib,
	packages	= theseus_packages + bld.engine_packages + bld.common_packages,
	source 		= theseus_src
)

