#! /usr/bin/env python
# encoding: utf-8
#
# Copyright 2011 Yorba Foundation

def build(bld):
	bld.common_src = [
	'../common/common-date.vala',
	'../common/common-intl.vala',
	'../common/common-yorba-application.vala'
	]
	
	bld.common_uselib = 'GLIB UNIQUE'
	bld.common_packages = ['glib-2.0', 'unique-1.0', 'posix' ]
	
	bld.engine_src = [
	'../engine/api/geary-abstract-account.vala',
	'../engine/api/geary-abstract-folder.vala',
	'../engine/api/geary-account.vala',
	'../engine/api/geary-credentials.vala',
	'../engine/api/geary-email-location.vala',
	'../engine/api/geary-email-properties.vala',
	'../engine/api/geary-email.vala',
	'../engine/api/geary-engine-account.vala',
	'../engine/api/geary-engine-error.vala',
	'../engine/api/geary-engine-folder.vala',
	'../engine/api/geary-engine.vala',
	'../engine/api/geary-folder-path.vala',
	'../engine/api/geary-folder-properties.vala',
	'../engine/api/geary-folder.vala',
	'../engine/api/geary-generic-imap-account.vala',
	'../engine/api/geary-gmail-account.vala',
	'../engine/api/geary-local-interfaces.vala',
	'../engine/api/geary-personality.vala',
	'../engine/api/geary-remote-interfaces.vala',
	'../engine/api/geary-special-folder.vala',
	
	'../engine/common/common-interfaces.vala',
	'../engine/common/common-message-data.vala',
	'../engine/common/common-nonblocking-mailbox.vala',
	'../engine/common/common-nonblocking-mutex.vala',
	'../engine/common/common-nonblocking-semaphore.vala',
	'../engine/common/common-string.vala',
	
	'../engine/imap/api/imap-account.vala',
	'../engine/imap/api/imap-email-location.vala',
	'../engine/imap/api/imap-email-properties.vala',
	'../engine/imap/api/imap-folder-properties.vala',
	'../engine/imap/api/imap-folder.vala',
	'../engine/imap/command/imap-command-response.vala',
	'../engine/imap/command/imap-commands.vala',
	'../engine/imap/command/imap-command.vala',
	'../engine/imap/decoders/imap-command-results.vala',
	'../engine/imap/decoders/imap-fetch-data-decoder.vala',
	'../engine/imap/decoders/imap-fetch-results.vala',
	'../engine/imap/decoders/imap-list-results.vala',
	'../engine/imap/decoders/imap-noop-results.vala',
	'../engine/imap/decoders/imap-select-examine-results.vala',
	'../engine/imap/decoders/imap-status-results.vala',
	'../engine/imap/imap-error.vala',
	'../engine/imap/message/imap-data-format.vala',
	'../engine/imap/message/imap-fetch-data-type.vala',
	'../engine/imap/message/imap-flag.vala',
	'../engine/imap/message/imap-message-data.vala',
	'../engine/imap/message/imap-message-set.vala',
	'../engine/imap/message/imap-parameter.vala',
	'../engine/imap/message/imap-tag.vala',
	'../engine/imap/response/imap-response-code-type.vala',
	'../engine/imap/response/imap-response-code.vala',
	'../engine/imap/response/imap-server-data-type.vala',
	'../engine/imap/response/imap-server-data.vala',
	'../engine/imap/response/imap-server-response.vala',
	'../engine/imap/response/imap-status-data-type.vala',
	'../engine/imap/response/imap-status-response.vala',
	'../engine/imap/response/imap-status.vala',
	'../engine/imap/transport/imap-client-connection.vala',
	'../engine/imap/transport/imap-client-session-manager.vala',
	'../engine/imap/transport/imap-client-session.vala',
	'../engine/imap/transport/imap-deserializer.vala',
	'../engine/imap/transport/imap-mailbox.vala',
	'../engine/imap/transport/imap-serializable.vala',
	'../engine/imap/transport/imap-serializer.vala',
	
	'../engine/rfc822/rfc822-mailbox-addresses.vala',
	'../engine/rfc822/rfc822-mailbox-address.vala',
	'../engine/rfc822/rfc822-message-data.vala',
	
	'../engine/sqlite/abstract/sqlite-database.vala',
	'../engine/sqlite/abstract/sqlite-row.vala',
	'../engine/sqlite/abstract/sqlite-table.vala',
	'../engine/sqlite/api/sqlite-account.vala',
	'../engine/sqlite/api/sqlite-folder.vala',
	'../engine/sqlite/email/sqlite-folder-row.vala',
	'../engine/sqlite/email/sqlite-folder-table.vala',
	'../engine/sqlite/email/sqlite-mail-database.vala',
	'../engine/sqlite/email/sqlite-message-location-row.vala',
	'../engine/sqlite/email/sqlite-message-location-table.vala',
	'../engine/sqlite/email/sqlite-message-row.vala',
	'../engine/sqlite/email/sqlite-message-table.vala',
	'../engine/sqlite/imap/sqlite-imap-message-location-properties-row.vala',
	'../engine/sqlite/imap/sqlite-imap-message-location-properties-table.vala',
	
	'../engine/state/state-machine-descriptor.vala',
	'../engine/state/state-machine.vala',
	'../engine/state/state-mapping.vala',
	
	'../engine/util/util-memory.vala',
	'../engine/util/util-reference-semantics.vala',
	'../engine/util/util-trillian.vala'
	]
	
	bld.engine_uselib = 'GLIB GEE GIO SQLHEAVY GMIME'
	bld.engine_packages = ['glib-2.0', 'gee-1.0', 'gio-2.0', 'sqlheavy-0.1', 'gmime-2.4']
	
	bld.recurse('client')
	bld.recurse('console')

