#! /usr/bin/env python
# encoding: utf-8
#
# Copyright 2011-2012 Yorba Foundation

def build(bld):
	bld.common_src = [
	'common/common-arrays.vala',
	'common/common-async.vala',
	'common/common-date.vala',
	'common/common-intl.vala',
	'common/common-yorba-application.vala'
	]
	
	bld.common_uselib = 'GLIB UNIQUE'
	bld.common_packages = ['glib-2.0', 'unique-3.0', 'posix' ]
	
	bld.engine_src = [
	'engine/api/geary-account.vala',
	'engine/api/geary-account-information.vala',
	'engine/api/geary-batch-operations.vala',
	'engine/api/geary-composed-email.vala',
	'engine/api/geary-conversation.vala',
	'engine/api/geary-conversations.vala',
	'engine/api/geary-credentials.vala',
	'engine/api/geary-email-flag.vala',
	'engine/api/geary-email-flags.vala',
	'engine/api/geary-email-identifier.vala',
	'engine/api/geary-email-properties.vala',
	'engine/api/geary-email.vala',
	'engine/api/geary-endpoint.vala',
	'engine/api/geary-engine-error.vala',
	'engine/api/geary-engine.vala',
	'engine/api/geary-folder-path.vala',
	'engine/api/geary-folder.vala',
	'engine/api/geary-logging.vala',
	'engine/api/geary-personality.vala',
	'engine/api/geary-service-provider.vala',
	'engine/api/geary-special-folder.vala',
	
	'engine/common/common-message-data.vala',
	
	'engine/imap/api/imap-account.vala',
	'engine/imap/api/imap-email-flags.vala',
	'engine/imap/api/imap-email-identifier.vala',
	'engine/imap/api/imap-email-properties.vala',
	'engine/imap/api/imap-folder-properties.vala',
	'engine/imap/api/imap-folder.vala',
	'engine/imap/command/imap-command-response.vala',
	'engine/imap/command/imap-commands.vala',
	'engine/imap/command/imap-command.vala',
	'engine/imap/command/imap-fetch-command.vala',
	'engine/imap/decoders/imap-command-results.vala',
	'engine/imap/decoders/imap-fetch-data-decoder.vala',
	'engine/imap/decoders/imap-fetch-results.vala',
	'engine/imap/decoders/imap-list-results.vala',
	'engine/imap/decoders/imap-select-examine-results.vala',
	'engine/imap/decoders/imap-status-results.vala',
	'engine/imap/imap-error.vala',
	'engine/imap/message/imap-data-format.vala',
	'engine/imap/message/imap-fetch-data-type.vala',
	'engine/imap/message/imap-fetch-body-data-type.vala',
	'engine/imap/message/imap-flag.vala',
	'engine/imap/message/imap-message-data.vala',
	'engine/imap/message/imap-message-set.vala',
	'engine/imap/message/imap-parameter.vala',
	'engine/imap/message/imap-tag.vala',
	'engine/imap/response/imap-continuation-response.vala',
	'engine/imap/response/imap-response-code-type.vala',
	'engine/imap/response/imap-response-code.vala',
	'engine/imap/response/imap-server-data-type.vala',
	'engine/imap/response/imap-server-data.vala',
	'engine/imap/response/imap-server-response.vala',
	'engine/imap/response/imap-status-data-type.vala',
	'engine/imap/response/imap-status-response.vala',
	'engine/imap/response/imap-status.vala',
	'engine/imap/response/imap-unsolicited-server-data.vala',
	'engine/imap/transport/imap-client-connection.vala',
	'engine/imap/transport/imap-client-session-manager.vala',
	'engine/imap/transport/imap-client-session.vala',
	'engine/imap/transport/imap-deserializer.vala',
	'engine/imap/transport/imap-mailbox.vala',
	'engine/imap/transport/imap-serializable.vala',
	'engine/imap/transport/imap-serializer.vala',
	
	'engine/impl/geary-abstract-account.vala',
	'engine/impl/geary-abstract-folder.vala',
	'engine/impl/geary-email-flag-watcher.vala',
	'engine/impl/geary-email-prefetcher.vala',
	'engine/impl/geary-engine-account.vala',
	'engine/impl/geary-generic-imap-account.vala',
	'engine/impl/geary-generic-imap-folder.vala',
	'engine/impl/geary-gmail-account.vala',
	'engine/impl/geary-yahoo-account.vala',
	'engine/impl/geary-other-account.vala',
	'engine/impl/geary-receive-replay-operations.vala',
	'engine/impl/geary-receive-replay-queue.vala',
	'engine/impl/geary-send-replay-operations.vala',
	'engine/impl/geary-send-replay-queue.vala',
	
	'engine/nonblocking/nonblocking-abstract-semaphore.vala',
	'engine/nonblocking/nonblocking-batch.vala',
	'engine/nonblocking/nonblocking-mailbox.vala',
	'engine/nonblocking/nonblocking-mutex.vala',
	'engine/nonblocking/nonblocking-variants.vala',
	
	'engine/rfc822/rfc822-error.vala',
	'engine/rfc822/rfc822-mailbox-addresses.vala',
	'engine/rfc822/rfc822-mailbox-address.vala',
	'engine/rfc822/rfc822-message.vala',
	'engine/rfc822/rfc822-message-data.vala',
	'engine/rfc822/rfc822-utils.vala',
	
	'engine/smtp/smtp-abstract-authenticator.vala',
	'engine/smtp/smtp-authenticator.vala',
	'engine/smtp/smtp-client-connection.vala',
	'engine/smtp/smtp-client-session.vala',
	'engine/smtp/smtp-command.vala',
	'engine/smtp/smtp-data-format.vala',
	'engine/smtp/smtp-error.vala',
	'engine/smtp/smtp-greeting.vala',
	'engine/smtp/smtp-login-authenticator.vala',
	'engine/smtp/smtp-plain-authenticator.vala',
	'engine/smtp/smtp-request.vala',
	'engine/smtp/smtp-response.vala',
	'engine/smtp/smtp-response-code.vala',
	'engine/smtp/smtp-response-line.vala',
	
	'engine/sqlite/abstract/sqlite-database.vala',
	'engine/sqlite/abstract/sqlite-row.vala',
	'engine/sqlite/abstract/sqlite-table.vala',
	'engine/sqlite/abstract/sqlite-transaction.vala',
	'engine/sqlite/api/sqlite-account.vala',
	'engine/sqlite/api/sqlite-folder.vala',
	'engine/sqlite/email/sqlite-folder-row.vala',
	'engine/sqlite/email/sqlite-folder-table.vala',
	'engine/sqlite/email/sqlite-mail-database.vala',
	'engine/sqlite/email/sqlite-message-location-row.vala',
	'engine/sqlite/email/sqlite-message-location-table.vala',
	'engine/sqlite/email/sqlite-message-row.vala',
	'engine/sqlite/email/sqlite-message-table.vala',
	'engine/sqlite/imap/sqlite-imap-database.vala',
	'engine/sqlite/imap/sqlite-imap-folder-properties-row.vala',
	'engine/sqlite/imap/sqlite-imap-folder-properties-table.vala',
	'engine/sqlite/imap/sqlite-imap-message-properties-row.vala',
	'engine/sqlite/imap/sqlite-imap-message-properties-table.vala',
	
	'engine/state/state-machine-descriptor.vala',
	'engine/state/state-machine.vala',
	'engine/state/state-mapping.vala',
	
	'engine/util/util-html.vala',
	'engine/util/util-inet.vala',
	'engine/util/util-interfaces.vala',
	'engine/util/util-memory.vala',
	'engine/util/util-numeric.vala',
	'engine/util/util-reference-semantics.vala',
	'engine/util/util-scheduler.vala',
	'engine/util/util-singleton.vala',
	'engine/util/util-stream.vala',
	'engine/util/util-string.vala',
	'engine/util/util-trillian.vala'
	]
	
	bld.engine_uselib = 'GLIB GEE GIO SQLHEAVY GMIME'
	bld.engine_packages = ['glib-2.0', 'gee-1.0', 'gio-2.0', 'sqlheavy-0.2', 'gmime-2.4']
	
	bld.stlib(
		target		= 'geary-static',
		vapi_dirs	= '../vapi',
		threading	= True,
		uselib		= bld.engine_uselib + ' ' + bld.common_uselib,
		packages	= bld.engine_packages + bld.common_packages,
		source 		= bld.common_src + bld.engine_src
	)
	
	bld.recurse('client')
	bld.recurse('console')
	bld.recurse('norman')
	bld.recurse('theseus')
	bld.recurse('dbusservice')

