#! /usr/bin/env python
# encoding: utf-8
#
# Copyright 2011-2012 Yorba Foundation

client_src = [
'geary-application.vala',
'geary-config.vala',
'geary-controller.vala',
'main.vala',

'ui/composer-window.vala',
'ui/geary-login.vala',
'ui/icon-factory.vala',
'ui/folder-list.vala',
'ui/main-toolbar.vala',
'ui/main-window.vala',
'ui/message-list-cell-renderer.vala',
'ui/message-list-store.vala',
'ui/message-list-view.vala',
'ui/message-viewer.vala',
'ui/preferences-dialog.vala',

'ui/sidebar/sidebar-branch.vala',
'ui/sidebar/sidebar-common.vala',
'ui/sidebar/sidebar-entry.vala',
'ui/sidebar/sidebar-tree.vala',

'util/util-email.vala',
'util/util-keyring.vala',
]

gsettings_schemas = [
'org.yorba.geary.gschema.xml'
]

client_uselib = 'GLIB GEE GTK GNOME-KEYRING WEBKITGTK JAVASCRIPTCOREGTK GTKSOURCEVIEW'
client_packages = [ 'gtk+-3.0', 'glib-2.0', 'gee-1.0', 'gnome-keyring-1', 'webkitgtk-3.0',
	'javascriptcoregtk-3.0', 'gtksourceview-3.0' ]

app = bld.program(
	target		= 'geary',
	vapi_dirs	= '../../vapi',
	threading	= True,
	uselib		= client_uselib + ' ' + bld.common_uselib + ' ' + bld.engine_uselib,
	packages	= client_packages + bld.common_packages + bld.engine_packages,
	source 		= client_src + bld.common_src + bld.engine_src
)

app.add_settings_schemas(gsettings_schemas)
app.process_settings()

