#! /usr/bin/env python
# encoding: utf-8
#
# Copyright 2011 Yorba Foundation

client_src = [
'geary-application.vala',
'main.vala',

'ui/folder-list-store.vala',
'ui/folder-list-view.vala',
'ui/main-window.vala',
'ui/message-buffer.vala',
'ui/message-list-store.vala',
'ui/message-list-view.vala',
'ui/message-viewer.vala',

'util/intl.vala'
]

client_uselib = 'GLIB GEE GTK'
client_packages = [ 'gtk+-2.0', 'glib-2.0', 'gee-1.0' ]

bld.program(
	target		= 'geary',
	vapi_dirs	= '../../vapi',
	threading	= True,
	uselib		= client_uselib + ' ' + bld.common_uselib + ' ' + bld.engine_uselib,
	packages	= client_packages + bld.common_packages + bld.engine_packages,
	source 		= client_src + bld.common_src + bld.engine_src
)

