#! /usr/bin/env python
# encoding: utf-8
#
# Copyright 2011-2012 Yorba Foundation

norman_src = [
'main.vala'
]

norman_uselib = 'GEE GTK GLIB'
norman_packages = [ 'gee-1.0', 'glib-2.0' ]

bld.program(
	target		= 'norman',
	vapi_dirs	= '../../vapi',
	threading	= True,
	use			='geary-static',
	uselib		= norman_uselib + ' ' + bld.engine_uselib + ' ' + bld.common_uselib,
	packages	= norman_packages + bld.engine_packages + bld.common_packages,
	source 		= norman_src
)

