#! /usr/bin/env python
# encoding: utf-8
#
# Copyright 2011-2012 Yorba Foundation

console_src = [
'main.vala'
]

console_uselib = 'GEE GTK GLIB'
console_packages = [ 'gee-1.0', 'gtk+-3.0', 'glib-2.0' ]

bld.program(
	target		= 'console',
	vapi_dirs	= '../../vapi',
	threading	= True,
	use			='geary-static',
	uselib		= console_uselib + ' ' + bld.engine_uselib + ' ' + bld.common_uselib,
	packages	= console_packages + bld.engine_packages + bld.common_packages,
	source 		= console_src
)

