#! /usr/bin/env python
# encoding: utf-8
#
# Copyright 2011-2012 Yorba Foundation

dbusservice_src = [
'controller.vala',
'database.vala',
'dbus-conversation.vala',
'dbus-conversations.vala',
'dbus-email.vala',
'main.vala'
]

dbusservice_uselib = 'GEE GLIB'
dbusservice_packages = [ 'gee-1.0', 'glib-2.0' ]

bld.program(
	target		= 'gearyd',
	vapi_dirs	= '../../vapi',
	threading	= True,
	uselib		= dbusservice_uselib + ' ' + bld.engine_uselib + ' ' + bld.common_uselib,
	packages	= dbusservice_packages + bld.engine_packages + bld.common_packages,
	source 		= dbusservice_src + bld.common_src + bld.engine_src
)

